services:
  backend:
    build: .
    container_name: finance-backend
    restart: unless-stopped
    ports:
      - "8000:8000"        # снаружи 8000, внутри 8000 (uvicorn)
    volumes:
      - ./backend_models:/app/backend_models:ro
      - ./data:/app/data:ro
