version: "3.9"

services:
  backend:
    build: .
    container_name: finance-backend
    ports:
      - "80:8000"        # Снаружи 80 (HTTP), внутри 8000 (uvicorn)
    env_file:
      - .env             # опционально, для FRONTEND_ORIGINS и прочих
    restart: unless-stopped
    volumes:
      - ./backend_models:/app/backend_models:ro
      - ./data:/app/data:ro
